# 프론트엔드 에러 핸들링

[[10분 테코톡] 밧드의 프론트엔드에서의 에러핸들링](https://www.youtube.com/watch?v=hQekqGONSlY&list=PLkfxusmKmLsNDGmER2tmrslpPOTfKhE7j&index=107)

## 에러 핸들링이란?

**코드 실행 ⇒ 에러 발생 ⇒ 예외 처리 ⇒ 실행 복구**

> 코드가 실행되고, 예상하거나 예상치 못한 부분에서 에러가 발생했을때, JS에서 기본적으로 제공되는 기능으로 어플리케이션의 중단을 막고, 실행흐름이 이어갈 수 있도록 복구하는 것
> 

## 에러 핸들링의 중요성

**1. 안정적인 서비스**

- 처음부터 에러 핸들링을 제대로 하지 않으면, 점점 다음과 같은 상황이 지속되면서 에러 핸들링이 어려워진다.
    - 어플리케이션이 규모가 커진다.
    - 로직이 복잡해진다.
- 서비스가 운영될때 어플리케이션이 중단될 수도 있다.

**2.사용자경험**

- 어플리케이션이 실행되며, 서버와 통신하는 중 에러가 발생하면
    - 어플리케이션이 중단될 수 있다.
    - 사용자의 화면이 멈추고, 사용자가 서비스를 이탈할 수 있다.
- 에러핸들링이 되어있다면
    - 에러가 발생했음을 사용자가 즉각적으로 알게된다.
    - 사용자가 인지하고 다음 행동을 취할 수 있게 해준다.

## 에러의 종류

**1.컴파일 에러**

- 자바스크립트 엔진이 코드를 읽으면서 발견되는 에러
    - 잘못된 구문
    - 유효하지 않은 자료형

**2.런타임 에러**

- 코드가 실행되고 발생하는 에러
    - `Undefined` 객체의 속성 참조
    - 무한루프

## 런타임 시점

**다음 두 상황은 코드를 읽는 시점에서는 문제가 없다.**

하지만 코드가 실행되면 에러가 발생한다.

```jsx
const a = null;
console.log(a.b);
// TypeError
```

```jsx
const price = 1200;
price.forEach(() => {});
// TypeError
```

## 자바스크립트 에러 객체

- Error : 기본적인 에러 객체
- EvalError : 전역 함수 `eval()`에서 발생하는 에러
- URIError : `encodeURI()`나 `decodeURI()` 함수에 부적절한 매개변수를 제공했을 때 발생
- SynTaxError : 문법이 틀렸을 때 발생
- ReferenceError : 잘못된 참조를 했을 때 발생
- RangeError : 숫자 변수가 범위를 벗어났을 때 발생
- TypeError : 변수나 매개변수가 유효한 자료형이 아님을 나타냄

## 런타임 에러 핸들링 방법

**try/cath**

```jsx
try{
	console.log('success');
}catch(error){
	console.log(error);
}
```

- `try`구문 안에 유효한 구문을 작성한다.
    - 만약 `try` 구문 안에 유효하지 않은 구문을 작성하면 `try`가 동작하지 못한다.
- `catch`구문 안에 유효한 구문을 작성한다.
    - `try`문에서 발생한 에러를 인수로 `error`로 받는다.
    - 해당 에러의 정보를 확인할 수 있다.
    

### 비동기 로직에서 try/catch 주의할 점

```jsx
async function personFetch(){
	try{
		// 옳은 방법
		// const res = await fetch('https://...');
		// console.log(res);
	
		// 틀린 방법
		fetch('https://...');
	}catch(error){
		console.error(error);
	}
}
```

- `await`를 작성하지 않으면
- `fetch`가 진행될 동안 해당 `try`문을 종료한다.
    - 만약 `fetch`가 `error`를 발생시키면 `catch`를 하지 못하고 전역 에러를 발생시킨다.

## 사용자 지정 에러

```jsx
function checkValue(value) {
	if(!value) {
		throw new Error("'App.js, ~~을 fetch하는 중에 에러 발생'");
	};

	return value;
};
```

- `value`가 없을때 error 객체를 발생하고 thorw한다.
    - 에러가 어떻게 발생했는지 알 수 있다.
    - 디버깅할때 에러를 빠르게 찾을 수 있다.

## try/catch를 많이 사용하면 좋지 않을까?

**아니다**

- try/catch를 많이 사용하면 분기처리가 되지 않기 때문에 어디서 에러가 발생했는지 찾기 힘들다.
    - 가독성이 떨어진다.
    - 유지보수에 걸림돌이 될 수 있다.

## 상황에 따른 처리방법

- 시나리오를 작성해서 다음과 같은 방법으로 처리할 수 있다.
    - 에러 페이지
    - 메시지
    - 별도 처리 없음

---

## 추가

**finally**

```jsx
try{
	// 예외발생할 가능성이 있는 문장
}catch(error){
	// 에러가 발생했을때 처리하기 위한 문장
}finally{
	// 예외 발생과 관계없이 항상 수행되어야 하는 문장
}
```

- 예외 발생시 `try` ⇒ `catch` ⇒ `finally` 순서
- 발생하지 않으면 `try` ⇒ `finally` 순서

---

## 참고자료

[Error - JavaScript | MDN](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)